"""Mode Share Estimator - scoring parameter calibration for MATSim experiments.

Two modes of operation:

  (a) Cold start (no --experiment-dir): "current" parameter values are read
      from matsim/configs/basic/config_full.xml (the documented MATSim defaults:
      pt.constant=0.0, walk.constant=0.0, waitingPt=-6.0). The recommended
      values come from an ACS-share tier table only as a seed for the very
      first run, and only if they differ materially from the MATSim defaults.

  (b) Iterative calibration (--experiment-dir <path>): reads the experiment's
      modestats.csv (realised mode shares at the final iteration) and the
      experiment's config.xml (the scoring params it actually ran with).
      Applies a clamped log-ratio update toward ACS targets:

          Delta = clip(0.5 * ln(ACS_share / sim_share), -1.0, +1.0)

      This is the standard alternative-specific-constant (ASC) update from
      discrete choice calibration. Delta is computed independently for
      pt.constant (toward ACS transit share) and walk.constant (toward ACS
      walk share). waitingPt is left at whatever the experiment used -
      tuning waitingPt iteratively is rarely the right lever.

  The transitRouter block (searchRadius, extensionRadius,
  maxBeelineWalkConnectionDistance, directWalkFactor) is updated via a
  separate tier-bump rule (see TRANSIT_ROUTER_TIERS): cold start seeds from
  ACS transit share, feedback bumps +/-1 tier when the realised PT share is
  outside [ROUTER_FEEDBACK_UNDER, ROUTER_FEEDBACK_OVER] of the ACS target.

Outputs:
    config/<region>/config_<stem>_estimated.json (single source of truth)
    logs/mode_share_estimator_YYYYMMDD_HHMMSS.log

At experiment time the MATSim config.xml is generated by ConfigManager from
the base template (matsim/configs/<mode>/config.xml) overlaid with the JSON's
matsim.configurable_params - this estimator does not write any XML.

Usage:
    # Cold start
    python estimators/mode_share_estimator.py config/USA/Birmingham_AL/config.json

    # Iterative calibration
    python estimators/mode_share_estimator.py config/USA/Birmingham_AL/config.json \
        --experiment-dir /path/to/experiments/experiment_20260511_140420
"""

import argparse
import copy
import csv
import json
import math
import sys
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

project_root = Path(__file__).parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from estimators.demand_estimator import (
    TeeWriter,
    fetch_acs_commute_data,
    apply_recommendations,
    resolve_estimator_inputs,
    require_acs_key,
    _print_acs_coverage_error,
    _resolve_experiment_dir,
)

# ---------------------------------------------------------------------------
# Tunables
# ---------------------------------------------------------------------------
# Standard discrete-choice ASC update: Delta = LOG_RATIO_GAIN * ln(target / sim),
# clamped to +/-MAX_STEP so one outlier iteration can't swing constants wildly.
LOG_RATIO_GAIN = 0.5
MAX_STEP       = 1.0

# Don't recommend a change smaller than this - within numerical noise of MATSim.
MIN_REPORT_DELTA = 0.05

# Floor on simulated shares to avoid ln(0) when a mode collapses entirely.
SIM_SHARE_FLOOR = 1e-4  # 0.01% - well below any ACS commute target.

# ---------------------------------------------------------------------------
# Cold-start tier table (only used when --experiment-dir is NOT provided)
# ---------------------------------------------------------------------------
# Each tier sets three MATSim scoring parameters:
#   pt.constant   - alternative-specific constant for PT mode choice
#   waitingPt     - disutility per hour of waiting at PT stops (util/hr)
#   walk.constant - alternative-specific constant for walk mode choice
#
# These are *seed* values for the very first run in a region. Once an
# experiment has been completed, the log-ratio update (Option 3) takes over
# and corrects from the realised shares - the tier table is no longer the
# target. For near-zero ACS regions the seed deliberately stays close to
# MATSim defaults (0.0, 0.0, -6.0) rather than baking in heavy a-priori
# penalties; the empirical correction does the work.

SCORING_TIERS: List[Tuple[float, Dict[str, float]]] = [
    # (min_transit_share, params)
    (0.30, {"pt.constant": 1.5,  "waitingPt": -1.0, "walk.constant": -1.5}),
    (0.10, {"pt.constant": 0.5,  "waitingPt": -1.5, "walk.constant": -2.0}),
    (0.05, {"pt.constant": 0.0,  "waitingPt": -2.0, "walk.constant": -2.5}),
    (0.01, {"pt.constant": 0.0,  "waitingPt": -3.0, "walk.constant": -1.0}),
    (0.00, {"pt.constant": 0.0,  "waitingPt": -3.0, "walk.constant": -1.0}),
]


# ---------------------------------------------------------------------------
# Transit router tier table (cold-start) + feedback rule
# ---------------------------------------------------------------------------
# These four params shape the PT *choice set*, not the utility:
#   searchRadius                     - radius around origin/dest to find stops
#   extensionRadius                  - growth step if no stop is found in radius
#   maxBeelineWalkConnectionDistance - max stop-to-stop / activity-to-stop walk
#   directWalkFactor                 - pt-vs-walk comparison threshold; the
#                                      router returns a direct walk whenever
#                                      direct_walk_time <= factor * pt_time
#
# Memory/CPU note: maxBeelineWalkConnectionDistance is the dangerous one.
# Transit-router graph cost scales ~O(N stops x density x radius^2). The 400m
# ceiling at the top tier matches the textbook "1/4 mile" walk-access standard
# without crossing into ranges that have caused OOM on Hermes for dense
# networks (Chicago, NYC) in prior runs.
#
# additionalTransferTime is intentionally NOT in this table — it is a
# behavior-realism knob, not a calibration lever for mode share.

TRANSIT_ROUTER_TIERS: List[Tuple[float, Dict[str, float]]] = [
    # (min_transit_share, params)
    (0.30, {"searchRadius": 1500.0, "extensionRadius": 300.0,
            "maxBeelineWalkConnectionDistance": 400.0, "directWalkFactor": 2.0}),
    (0.10, {"searchRadius": 1200.0, "extensionRadius": 250.0,
            "maxBeelineWalkConnectionDistance": 350.0, "directWalkFactor": 1.8}),
    (0.05, {"searchRadius": 1000.0, "extensionRadius": 200.0,
            "maxBeelineWalkConnectionDistance": 300.0, "directWalkFactor": 1.5}),
    (0.00, {"searchRadius": 1000.0, "extensionRadius": 200.0,
            "maxBeelineWalkConnectionDistance": 250.0, "directWalkFactor": 1.3}),
]

TRANSIT_ROUTER_PARAMS = (
    "searchRadius",
    "extensionRadius",
    "maxBeelineWalkConnectionDistance",
    "directWalkFactor",
)

# MATSim documented defaults (used as the "current" baseline when the
# experiment's config.xml has no transitRouter block, e.g. very first run).
_TRANSIT_ROUTER_DEFAULTS_FALLBACK = {
    "searchRadius":                     1000.0,
    "extensionRadius":                  200.0,
    "maxBeelineWalkConnectionDistance": 100.0,
    "directWalkFactor":                 1.0,
}

# Feedback rule thresholds: if sim_pt / acs_pt is below UNDER or above OVER,
# bump router params one tier (toward more / less PT availability). Otherwise
# leave them alone and let the scoring constants do the fine-grained work.
ROUTER_FEEDBACK_UNDER = 0.7   # sim < 70% of target -> bump up one tier
ROUTER_FEEDBACK_OVER  = 1.3   # sim > 130% of target -> bump down one tier


# ---------------------------------------------------------------------------
# Tier lookup (cold-start only)
# ---------------------------------------------------------------------------

def _select_tier(transit_share: float) -> Tuple[Dict[str, float], str]:
    for min_share, params in SCORING_TIERS:
        if transit_share >= min_share:
            if min_share == 0.30:
                label = f"NYC-class (>{min_share:.0%})"
            elif min_share == 0.10:
                label = f"high-transit ({min_share:.0%}-30%)"
            elif min_share == 0.05:
                label = f"moderate-transit ({min_share:.0%}-10%)"
            elif min_share == 0.01:
                label = f"low-transit ({min_share:.0%}-5%)"
            else:
                label = "near-zero transit (under 1%)"
            return params, label
    return SCORING_TIERS[-1][1], "near-zero transit (under 1%)"


def _select_router_tier(transit_share: float) -> Tuple[int, Dict[str, float], str]:
    """Return (tier_index, params, label) for the matching transit-router tier.

    tier_index = 0 is the most pt-aggressive (NYC-class), len-1 is the most
    conservative (low-transit). The index is what the feedback rule increments
    or decrements when bumping tiers.
    """
    for idx, (min_share, params) in enumerate(TRANSIT_ROUTER_TIERS):
        if transit_share >= min_share:
            if min_share == 0.30:
                label = f"very-high transit (>={min_share:.0%}) — NYC-class"
            elif min_share == 0.10:
                label = f"high transit ({min_share:.0%}-30%)"
            elif min_share == 0.05:
                label = f"moderate transit ({min_share:.0%}-10%)"
            else:
                label = f"low transit (<{TRANSIT_ROUTER_TIERS[-2][0]:.0%})"
            return idx, params, label
    last = len(TRANSIT_ROUTER_TIERS) - 1
    return last, TRANSIT_ROUTER_TIERS[last][1], "low transit (<5%)"


def _router_params_at_tier(idx: int) -> Dict[str, float]:
    """Clamp idx to a valid tier and return that tier's router params."""
    idx = max(0, min(idx, len(TRANSIT_ROUTER_TIERS) - 1))
    return dict(TRANSIT_ROUTER_TIERS[idx][1])


def _router_feedback_direction(sim_pt: float, acs_pt: float) -> int:
    """Return -1 (bump up tier), +1 (bump down), or 0 (hold).

    Bumping "up a tier" means moving to a lower index in TRANSIT_ROUTER_TIERS
    (= more aggressive PT availability), hence -1. "Down a tier" is the
    opposite direction. Returns 0 inside the dead-band so the router params
    don't oscillate every iteration — let the scoring constants do the fine
    correction.
    """
    if acs_pt <= SIM_SHARE_FLOOR:
        return 0
    ratio = max(sim_pt, SIM_SHARE_FLOOR) / acs_pt
    if ratio < ROUTER_FEEDBACK_UNDER:
        return -1
    if ratio > ROUTER_FEEDBACK_OVER:
        return +1
    return 0


# ---------------------------------------------------------------------------
# ACS aggregation
# ---------------------------------------------------------------------------

def _aggregate_acs(acs_data: Dict[str, Dict[str, int]]) -> Dict[str, Any]:
    """Sum ACS B08301 fields across all counties and compute shares."""
    totals: Dict[str, int] = {}
    for county_data in acs_data.values():
        for key, val in county_data.items():
            totals[key] = totals.get(key, 0) + val

    total_workers = max(totals.get("total_workers", 0), 1)
    transit_total = totals.get("public_transit", 0)
    bus           = totals.get("bus", 0)
    subway        = totals.get("subway", 0)
    commuter_rail = totals.get("commuter_rail", 0)
    light_rail    = totals.get("light_rail", 0)
    walked        = totals.get("walked", 0)
    car           = totals.get("car_truck_van", 0)

    return {
        "total_workers":   total_workers,
        "transit_share":   transit_total / total_workers,
        "bus_share":       bus / total_workers,
        "rail_share":      (subway + commuter_rail + light_rail) / total_workers,
        "walk_share":      walked / total_workers,
        "car_share":       car / total_workers,
    }


# ---------------------------------------------------------------------------
# Reading "current" param values from MATSim XML
# ---------------------------------------------------------------------------
# Precedence: experiment's config.xml (if --experiment-dir) ->
#             config_full.xml documented defaults.
# We deliberately do NOT read the region's config.xml here, because that file
# is mode_share_estimator's *own previous output* - using it as "current"
# would create a self-referencing loop.

_FULL_DEFAULTS_FALLBACK = {
    "pt.constant":   0.0,
    "waitingPt":     -6.0,
    "walk.constant": 0.0,
}


def _read_scoring_params_from_xml(xml_path: Path) -> Dict[str, float]:
    """Parse pt.constant, walk.constant, waitingPt from a MATSim config.xml.

    Missing params fall back to the MATSim documented defaults
    (pt.constant=0.0, walk.constant=0.0, waitingPt=-6.0). An empty modeParams
    block means MATSim uses its default - same as the param being absent.
    """
    result = dict(_FULL_DEFAULTS_FALLBACK)
    if not xml_path.is_file():
        return result

    tree = ET.parse(xml_path)
    root = tree.getroot()
    scoring = next(
        (m for m in root.findall("module") if m.get("name") == "scoring"), None
    )
    if scoring is None:
        return result

    sp = scoring.find("parameterset[@type='scoringParameters']")
    if sp is None:
        return result

    waiting = sp.find("param[@name='waitingPt']")
    if waiting is not None:
        try:
            result["waitingPt"] = float(waiting.get("value"))
        except (TypeError, ValueError):
            pass

    for ps in sp.findall("parameterset[@type='modeParams']"):
        mode_el = ps.find("param[@name='mode']")
        if mode_el is None:
            continue
        mode_name = mode_el.get("value")
        const_el = ps.find("param[@name='constant']")
        if const_el is None:
            continue
        try:
            value = float(const_el.get("value"))
        except (TypeError, ValueError):
            continue
        if mode_name == "pt":
            result["pt.constant"] = value
        elif mode_name == "walk":
            result["walk.constant"] = value

    return result


def _read_transit_router_params_from_xml(xml_path: Path) -> Dict[str, float]:
    """Parse searchRadius, extensionRadius, maxBeelineWalkConnectionDistance,
    directWalkFactor from a MATSim config.xml. Missing params fall back to the
    MATSim documented defaults.
    """
    result = dict(_TRANSIT_ROUTER_DEFAULTS_FALLBACK)
    if not xml_path.is_file():
        return result

    tree = ET.parse(xml_path)
    root = tree.getroot()
    router = next(
        (m for m in root.findall("module") if m.get("name") == "transitRouter"), None
    )
    if router is None:
        return result

    for name in TRANSIT_ROUTER_PARAMS:
        el = router.find(f"param[@name='{name}']")
        if el is None:
            continue
        try:
            result[name] = float(el.get("value"))
        except (TypeError, ValueError):
            pass
    return result


def _read_full_xml_defaults() -> Dict[str, float]:
    full_path = project_root / "matsim" / "configs" / "basic" / "config_full.xml"
    if full_path.is_file():
        return _read_scoring_params_from_xml(full_path)
    return dict(_FULL_DEFAULTS_FALLBACK)


# ---------------------------------------------------------------------------
# Reading modestats.csv from a finished experiment
# ---------------------------------------------------------------------------

def _read_modestats_final(exp_dir: Path) -> Optional[Dict[str, float]]:
    """Return final-iteration mode shares from an experiment's modestats.

    Looks for modestats in the canonical locations: experiment root, or
    output/. Returns None if no file is found or it is unparseable.
    """
    candidates = [
        exp_dir / "modestats.csv",
        exp_dir / "output" / "modestats.csv",
        exp_dir / "modestats.txt",
        exp_dir / "output" / "modestats.txt",
    ]
    path = next((p for p in candidates if p.is_file()), None)
    if path is None:
        return None

    # The file is semicolon-separated despite the .csv extension.
    with open(path, newline="") as f:
        sample = f.read(2048)
        f.seek(0)
        try:
            dialect = csv.Sniffer().sniff(sample, delimiters=";,\t")
        except csv.Error:
            dialect = csv.excel
            dialect.delimiter = ";"
        reader = csv.DictReader(f, dialect=dialect)
        rows = list(reader)

    if not rows:
        return None

    # Pick the row with the highest "iteration" value (final).
    def _iter_of(r: Dict[str, str]) -> int:
        try:
            return int(r.get("iteration", "0"))
        except ValueError:
            return -1

    final_row = max(rows, key=_iter_of)
    shares: Dict[str, float] = {}
    for k, v in final_row.items():
        if k == "iteration" or v is None:
            continue
        try:
            shares[k] = float(v)
        except ValueError:
            continue
    shares["_iteration"] = float(_iter_of(final_row))
    return shares


def _read_exp_config_xml(exp_dir: Path) -> Optional[Path]:
    """Locate the config.xml used for an experiment."""
    candidates = [
        exp_dir / "config.xml",
        exp_dir / "output" / "output_config.xml",
        exp_dir / "output_config.xml",
    ]
    return next((p for p in candidates if p.is_file()), None)


# ---------------------------------------------------------------------------
# Recommendation builders
# ---------------------------------------------------------------------------

PARAM_PATH_MAP = {
    "pt.constant":   "matsim.configurable_params.scoring.modeParams.pt.constant",
    "waitingPt":     "matsim.configurable_params.scoring.waitingPt",
    "walk.constant": "matsim.configurable_params.scoring.modeParams.walk.constant",
}

ROUTER_PARAM_PATH_MAP = {
    name: f"matsim.configurable_params.transitRouter.{name}"
    for name in TRANSIT_ROUTER_PARAMS
}


def _clamped_log_ratio(target: float, sim: float) -> float:
    sim = max(sim, SIM_SHARE_FLOOR)
    target = max(target, SIM_SHARE_FLOOR)
    raw = LOG_RATIO_GAIN * math.log(target / sim)
    return max(-MAX_STEP, min(MAX_STEP, raw))


def build_cold_start_recommendations(
    transit_share: float,
    tier_params: Dict[str, float],
    tier_label: str,
    acs_walk_share: float,
    current_values: Dict[str, float],
) -> List[Dict[str, Any]]:
    """Cold-start: recommend the tier-table seed where it differs from current."""
    reasons = {
        "pt.constant": (
            f"Cold start (no prior experiment). ACS transit share {transit_share:.2%} "
            f"({tier_label}). Seeding pt.constant={tier_params['pt.constant']:+.1f}; "
            f"subsequent runs with --experiment-dir will correct toward ACS using "
            f"the clamped log-ratio update."
        ),
        "waitingPt": (
            f"Cold start (no prior experiment). Seeding waitingPt="
            f"{tier_params['waitingPt']:.1f} util/hr for transit density "
            f"{transit_share:.2%} ({tier_label})."
        ),
        "walk.constant": (
            f"Cold start (no prior experiment). ACS walk share {acs_walk_share:.2%}. "
            f"Seeding walk.constant={tier_params['walk.constant']:+.1f}; subsequent "
            f"runs will correct toward ACS using the clamped log-ratio update."
        ),
    }

    recs = []
    for short_key in ("pt.constant", "waitingPt", "walk.constant"):
        recommended = tier_params[short_key]
        current     = current_values[short_key]
        if abs(recommended - current) > MIN_REPORT_DELTA:
            recs.append({
                "parameter":   PARAM_PATH_MAP[short_key],
                "current":     current,
                "recommended": recommended,
                "reason":      reasons[short_key],
            })
    return recs


def build_feedback_recommendations(
    acs: Dict[str, float],
    sim: Dict[str, float],
    current_values: Dict[str, float],
) -> List[Dict[str, Any]]:
    """Iterative: apply Delta = clip(0.5*ln(ACS/sim), -1, +1) for pt and walk."""
    acs_pt   = acs["transit_share"]
    acs_walk = acs["walk_share"]
    sim_pt   = sim.get("pt", 0.0)
    sim_walk = sim.get("walk", 0.0)

    delta_pt   = _clamped_log_ratio(acs_pt,   sim_pt)
    delta_walk = _clamped_log_ratio(acs_walk, sim_walk)

    new_pt   = round(current_values["pt.constant"]   + delta_pt,   3)
    new_walk = round(current_values["walk.constant"] + delta_walk, 3)

    iter_label = f"iter {int(sim.get('_iteration', 0))}"

    reasons = {
        "pt.constant": (
            f"Realised sim PT share at {iter_label} = {sim_pt:.2%} vs. ACS target "
            f"{acs_pt:.2%}. Deltapt.constant = clip({LOG_RATIO_GAIN}*ln({acs_pt:.4f}/"
            f"{max(sim_pt, SIM_SHARE_FLOOR):.4f}), +/-{MAX_STEP}) = {delta_pt:+.3f}. "
            f"New value: {current_values['pt.constant']:+.3f} -> {new_pt:+.3f}."
        ),
        "walk.constant": (
            f"Realised sim walk share at {iter_label} = {sim_walk:.2%} vs. ACS "
            f"target {acs_walk:.2%}. Deltawalk.constant = clip({LOG_RATIO_GAIN}*ln("
            f"{acs_walk:.4f}/{max(sim_walk, SIM_SHARE_FLOOR):.4f}), +/-{MAX_STEP}) = "
            f"{delta_walk:+.3f}. New value: {current_values['walk.constant']:+.3f} "
            f"-> {new_walk:+.3f}."
        ),
    }

    recs = []
    for short_key, new_value in (("pt.constant", new_pt), ("walk.constant", new_walk)):
        if abs(new_value - current_values[short_key]) > MIN_REPORT_DELTA:
            recs.append({
                "parameter":   PARAM_PATH_MAP[short_key],
                "current":     current_values[short_key],
                "recommended": new_value,
                "reason":      reasons[short_key],
            })

    # waitingPt is intentionally left at the experiment's value: it is a
    # physically interpretable disutility (util/hr of waiting), not a free
    # calibration knob, and tuning it iteratively conflates network supply
    # quality with preference parameters.

    return recs


def build_router_cold_start_recommendations(
    transit_share: float,
    tier_params: Dict[str, float],
    tier_label: str,
    current_values: Dict[str, float],
) -> List[Dict[str, Any]]:
    """Cold-start: recommend the router tier-table seed where it differs."""
    reason_common = (
        f"Cold start (no prior experiment). ACS transit share {transit_share:.2%} "
        f"({tier_label}). Seeding transit-router params from tier table; "
        f"subsequent runs with --experiment-dir adjust by one tier when "
        f"realised PT share is outside [{ROUTER_FEEDBACK_UNDER:.0%}, "
        f"{ROUTER_FEEDBACK_OVER:.0%}] of the ACS target."
    )
    recs: List[Dict[str, Any]] = []
    for name in TRANSIT_ROUTER_PARAMS:
        recommended = tier_params[name]
        current     = current_values[name]
        if abs(recommended - current) > 1e-6:
            recs.append({
                "parameter":   ROUTER_PARAM_PATH_MAP[name],
                "current":     current,
                "recommended": recommended,
                "reason":      reason_common + f" Setting {name}={recommended}.",
            })
    return recs


def build_router_feedback_recommendations(
    acs: Dict[str, float],
    sim: Dict[str, float],
    current_values: Dict[str, float],
) -> List[Dict[str, Any]]:
    """Iterative: bump router params one tier up/down based on sim_pt vs ACS.

    Strategy:
      - Find the tier whose params best match the experiment's current values.
      - If sim_pt is far below ACS, bump UP one tier (more PT availability).
      - If sim_pt is far above ACS, bump DOWN one tier.
      - Otherwise, leave router params alone — let pt.constant fine-tune.
    """
    acs_pt = acs["transit_share"]
    sim_pt = sim.get("pt", 0.0)

    direction = _router_feedback_direction(sim_pt, acs_pt)
    if direction == 0:
        return []

    # Identify the experiment's current tier by finding the closest match.
    # Distance is sum of relative differences across the four router params.
    def _dist(tier_idx: int) -> float:
        tp = TRANSIT_ROUTER_TIERS[tier_idx][1]
        d = 0.0
        for name in TRANSIT_ROUTER_PARAMS:
            ref = max(abs(tp[name]), 1e-3)
            d += abs(current_values[name] - tp[name]) / ref
        return d

    current_tier = min(range(len(TRANSIT_ROUTER_TIERS)), key=_dist)
    target_tier  = current_tier + direction
    target_tier  = max(0, min(target_tier, len(TRANSIT_ROUTER_TIERS) - 1))

    if target_tier == current_tier:
        # Already at the boundary tier in the requested direction; nothing to do.
        return []

    target_params = _router_params_at_tier(target_tier)
    iter_label = f"iter {int(sim.get('_iteration', 0))}"
    arrow = "up (more PT)" if direction == -1 else "down (less PT)"
    ratio = sim_pt / max(acs_pt, SIM_SHARE_FLOOR) if acs_pt > 0 else 0.0
    reason_common = (
        f"Realised sim PT share at {iter_label} = {sim_pt:.2%} vs. ACS target "
        f"{acs_pt:.2%} (ratio {ratio:.2f}). Outside dead-band "
        f"[{ROUTER_FEEDBACK_UNDER}, {ROUTER_FEEDBACK_OVER}] -> bumping router "
        f"tier {arrow}: tier {current_tier} -> tier {target_tier}."
    )

    recs: List[Dict[str, Any]] = []
    for name in TRANSIT_ROUTER_PARAMS:
        recommended = target_params[name]
        current     = current_values[name]
        if abs(recommended - current) > 1e-6:
            recs.append({
                "parameter":   ROUTER_PARAM_PATH_MAP[name],
                "current":     current,
                "recommended": recommended,
                "reason":      reason_common + f" Setting {name}={recommended}.",
            })
    return recs


def update_estimated_config(
    config: Dict[str, Any],
    estimated_path: Path,
    recommendations: List[Dict[str, Any]],
) -> Path:
    """Apply recommendations to the existing estimated config (or to `config`
    if no prior estimated file exists) and write to estimated_path. Merging
    onto an existing file preserves sibling-estimator adjustments from the
    same run (demand writes first, then mode-share)."""
    if estimated_path.exists():
        with open(estimated_path) as f:
            base = json.load(f)
        print(f"  Updating existing estimated config: {estimated_path.name}")
    else:
        base = copy.deepcopy(config)
        print(f"  Creating new estimated config: {estimated_path.name}")

    new_config = apply_recommendations(base, recommendations)
    new_config.pop("_config_dir", None)
    # Activity typicalDurations are derived from the survey on every run
    # and recorded in config_used.json as provenance. Carrying them into a
    # region config would freeze one run's values.
    new_config.get("matsim", {}).pop("_survey_typical_durations", None)

    with open(estimated_path, "w") as f:
        json.dump(new_config, f, indent=2)

    return estimated_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Mode share estimator - calibrate MATSim scoring params from ACS and prior experiments"
    )
    parser.add_argument(
        "config_or_region",
        help="Cold start: path to config JSON (e.g. config/USA/Birmingham_AL/config.json). "
             "Feedback (with --experiment-dir): path to the region folder - the "
             "estimator reads <experiment-dir>/config_used.json as the state to update.",
    )
    parser.add_argument(
        "--experiment-dir",
        type=str,
        default=None,
        help="Path to a prior experiment folder. When provided, the positional arg "
             "must be a region folder. The estimator reads modestats.csv and "
             "config.xml from this folder for the feedback signal, reads "
             "config_used.json as the state to update, and writes "
             "<region_folder>/config_estimated.json.",
    )
    args = parser.parse_args()

    logs_dir = project_root / "logs"
    logs_dir.mkdir(exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_path = logs_dir / f"mode_share_estimator_{timestamp}.log"
    tee = TeeWriter(log_path)
    sys.stdout = tee

    print("=" * 70)
    print("  MODE SHARE ESTIMATOR")
    print(f"  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 70)

    read_from, output_path = resolve_estimator_inputs(
        args.config_or_region, args.experiment_dir
    )

    with open(read_from) as f:
        config = json.load(f)

    print(f"\nLoaded config : {read_from}")
    print(f"Output target : {output_path}")
    counties = config.get("region", {}).get("counties", [])
    print(f"Region        : {len(counties)} counties")

    # ------------------------------------------------------------------
    # Step 1: Determine MODE (cold start vs. feedback) and read "current"
    # ------------------------------------------------------------------
    print()
    print("-" * 70)
    print("  STEP 1: DETERMINE OPERATING MODE & READ CURRENT PARAMS")
    print("-" * 70)

    exp_dir: Optional[Path] = None
    sim_shares: Optional[Dict[str, float]] = None
    current_values: Dict[str, float]
    current_router: Dict[str, float]
    current_source: str

    if args.experiment_dir:
        exp_dir = _resolve_experiment_dir(args.experiment_dir)

        sim_shares = _read_modestats_final(exp_dir)
        if sim_shares is None:
            print(f"ERROR: no modestats.csv/txt found in {exp_dir} or {exp_dir}/output")
            sys.exit(1)

        exp_xml = _read_exp_config_xml(exp_dir)
        if exp_xml is None:
            print(f"ERROR: no config.xml or output/output_config.xml in {exp_dir}")
            sys.exit(1)

        current_values = _read_scoring_params_from_xml(exp_xml)
        current_router = _read_transit_router_params_from_xml(exp_xml)
        current_source = f"experiment config.xml ({exp_xml.name})"
        print(f"  Mode             : FEEDBACK (iterative calibration)")
        print(f"  Experiment dir   : {exp_dir}")
        print(f"  Read modestats   : {sim_shares.get('_iteration', '?'):.0f} iterations")
        print(f"  Current params   : from {current_source}")
    else:
        current_values = _read_full_xml_defaults()
        # Cold start: there is no prior experiment; use MATSim's documented
        # transitRouter defaults as the "current" baseline. The tier table
        # decides what to seed from there.
        current_router = dict(_TRANSIT_ROUTER_DEFAULTS_FALLBACK)
        current_source = "matsim/configs/basic/config_full.xml (MATSim defaults)"
        print(f"  Mode             : COLD START (no --experiment-dir)")
        print(f"  Current params   : from {current_source}")

    print()
    print(f"  {'Parameter':<32}  {'Current':>10}")
    print(f"  {'-'*32}  {'-'*10}")
    print(f"  {'pt.constant':<32}  {current_values['pt.constant']:>+10.3f}")
    print(f"  {'waitingPt':<32}  {current_values['waitingPt']:>10.3f}")
    print(f"  {'walk.constant':<32}  {current_values['walk.constant']:>+10.3f}")
    for name in TRANSIT_ROUTER_PARAMS:
        print(f"  {'transitRouter.' + name:<32}  {current_router[name]:>10.2f}")

    # ------------------------------------------------------------------
    # Step 2: Fetch ACS targets
    # ------------------------------------------------------------------
    print()
    print("-" * 70)
    print("  STEP 2: FETCH ACS B08301 COMMUTE MODE DATA")
    print("-" * 70)

    # ACS is required: without real targets the clamped log-ratio update
    # would drive pt/walk constants toward zero shares, corrupting the
    # config. require_acs_key() exits if the key is missing, and a low-
    # coverage fetch is treated the same way.
    api_key = require_acs_key(config, read_from)
    acs_data: Dict[str, Dict[str, int]] = {}
    fips_list = [c for c in counties if isinstance(c, str)]
    if fips_list:
        print(f"  Fetching ACS for {len(fips_list)} counties ...")
        acs_data = fetch_acs_commute_data(fips_list, api_key)
        print(f"  Received data for {len(acs_data)}/{len(fips_list)} counties")
        coverage = len(acs_data) / len(fips_list)
        if coverage < 0.5:
            _print_acs_coverage_error(fips_list, list(acs_data.keys()))
            sys.exit(3)

    acs = _aggregate_acs(acs_data)

    print()
    print(f"  Total workers (ACS)  : {acs['total_workers']:,}")
    print(f"  ACS car share        : {acs['car_share']:.2%}")
    print(f"  ACS transit share    : {acs['transit_share']:.2%}")
    print(f"    Bus                : {acs['bus_share']:.2%}")
    print(f"    Rail               : {acs['rail_share']:.2%}")
    print(f"  ACS walk share       : {acs['walk_share']:.2%}")

    # ------------------------------------------------------------------
    # Step 3: Build recommendations
    # ------------------------------------------------------------------
    print()
    print("-" * 70)
    print("  STEP 3: BUILD RECOMMENDATIONS")
    print("-" * 70)

    if sim_shares is not None:
        # FEEDBACK mode
        print(f"  Realised shares at iter {int(sim_shares.get('_iteration', 0))}:")
        print(f"    car                : {sim_shares.get('car', 0):.2%}")
        print(f"    pt                 : {sim_shares.get('pt', 0):.2%}")
        print(f"    walk               : {sim_shares.get('walk', 0):.2%}")
        print()
        recommendations = build_feedback_recommendations(acs, sim_shares, current_values)
        router_recs = build_router_feedback_recommendations(acs, sim_shares, current_router)
        recommendations += router_recs
    else:
        # COLD START mode
        tier_params, tier_label = _select_tier(acs["transit_share"])
        _, router_tier_params, router_tier_label = _select_router_tier(acs["transit_share"])
        print(f"  Cold-start scoring tier : {tier_label}")
        print(f"  Seed scoring values     : pt.constant={tier_params['pt.constant']:+.1f}, "
              f"waitingPt={tier_params['waitingPt']:.1f}, "
              f"walk.constant={tier_params['walk.constant']:+.1f}")
        print(f"  Cold-start router tier  : {router_tier_label}")
        print(f"  Seed router values      : "
              f"searchRadius={router_tier_params['searchRadius']:.0f}, "
              f"extensionRadius={router_tier_params['extensionRadius']:.0f}, "
              f"maxBeelineWalk={router_tier_params['maxBeelineWalkConnectionDistance']:.0f}, "
              f"directWalkFactor={router_tier_params['directWalkFactor']:.1f}")
        recommendations = build_cold_start_recommendations(
            acs["transit_share"], tier_params, tier_label,
            acs["walk_share"], current_values,
        )
        router_recs = build_router_cold_start_recommendations(
            acs["transit_share"], router_tier_params, router_tier_label, current_router,
        )
        recommendations += router_recs

    if not recommendations:
        print("  No changes needed - current params already match the target.")
    else:
        print(f"  {len(recommendations)} parameter(s) to update:")
        for rec in recommendations:
            parts = rec["parameter"].split(".")
            if rec["parameter"].endswith(".constant"):
                short = parts[-2] + "." + parts[-1]
            elif "transitRouter" in rec["parameter"]:
                short = "router." + parts[-1]
            else:
                short = parts[-1]
            print(f"    {short:<28}  {rec['current']:>10.3f}  ->  {rec['recommended']:>10.3f}")
            print(f"      reason: {rec['reason']}")

    # Collect the final per-param values for the SUMMARY display. These are
    # not written to any XML - they just mirror what apply_recommendations
    # will write into the JSON in Step 4 below.
    final_params = {
        "pt.constant":   current_values["pt.constant"],
        "waitingPt":     current_values["waitingPt"],
        "walk.constant": current_values["walk.constant"],
    }
    router_final = dict(current_router)
    for rec in recommendations:
        path = rec["parameter"]
        leaf = path.split(".")[-1]
        if path.startswith("matsim.configurable_params.transitRouter."):
            router_final[leaf] = rec["recommended"]
        elif leaf == "waitingPt":
            final_params["waitingPt"] = rec["recommended"]
        elif leaf == "constant":
            mode_name = path.split(".")[-2]
            if mode_name == "pt":
                final_params["pt.constant"] = rec["recommended"]
            elif mode_name == "walk":
                final_params["walk.constant"] = rec["recommended"]

    # ------------------------------------------------------------------
    # Step 4: Update config_estimated.json (the single source of truth)
    # ------------------------------------------------------------------
    # At experiment time ConfigManager overlays this JSON's
    # matsim.configurable_params onto the base MATSim template
    # (matsim/configs/<mode>/config.xml). The estimator no longer writes
    # a region-specific config.xml - the JSON is the only output.
    print()
    print("-" * 70)
    print("  STEP 4: UPDATE config_estimated.json")
    print("-" * 70)

    if recommendations:
        estimated_path = update_estimated_config(config, output_path, recommendations)
        print(f"  Written: {estimated_path}")
    else:
        estimated_path = None
        print("  No changes - config_estimated.json not modified.")

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    print()
    print("=" * 70)
    print("  SUMMARY")
    print("=" * 70)
    if sim_shares is not None:
        print(f"  Mode                     : FEEDBACK")
        print(f"  Experiment               : {exp_dir.name if exp_dir else ''}")
        print(f"  Final iter PT share      : {sim_shares.get('pt', 0):.2%}  (ACS: {acs['transit_share']:.2%})")
        print(f"  Final iter walk share    : {sim_shares.get('walk', 0):.2%}  (ACS: {acs['walk_share']:.2%})")
    else:
        print(f"  Mode                     : COLD START")
        print(f"  ACS transit share        : {acs['transit_share']:.2%}")
    print(f"  pt.constant              : {current_values['pt.constant']:+.3f} -> {final_params['pt.constant']:+.3f}")
    print(f"  waitingPt                : {current_values['waitingPt']:.3f} -> {final_params['waitingPt']:.3f}")
    print(f"  walk.constant            : {current_values['walk.constant']:+.3f} -> {final_params['walk.constant']:+.3f}")
    for name in TRANSIT_ROUTER_PARAMS:
        print(f"  router.{name:<18}: {current_router[name]:>8.2f} -> {router_final[name]:>8.2f}")
    print()
    if estimated_path is not None:
        print(f"  estimated   -> {estimated_path}")
    print(f"  log         -> {log_path}")
    print()

    tee.close()
    sys.stdout = tee.terminal


if __name__ == "__main__":
    main()
